//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Banks = new HashSet<Bank>();
            this.DistributorClientAddresses = new HashSet<DistributorClientAddress>();
        }
    
        public int ID { get; set; }
        public string Iso2 { get; set; }
        public string Iso3 { get; set; }
        public int IsoCountryNumber { get; set; }
        public Nullable<int> DialingPrefix { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public bool HasLocationData { get; set; }
    
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual ICollection<DistributorClientAddress> DistributorClientAddresses { get; set; }
    }
}
