//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorClientAddress
    {
        public DistributorClientAddress()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Invoices1 = new HashSet<Invoice>();
        }
    
        public int ID { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string PostCode { get; set; }
        public int Country { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string CompanyName { get; set; }
        public string State { get; set; }
        public Nullable<int> Port { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> AddressType { get; set; }
        public bool IsAdelaideWarehouse { get; set; }
        public Nullable<int> IndicoDistributorClientAddressId { get; set; }
        public string DistributorName { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Invoice> Invoices1 { get; set; }
    }
}
