//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetInvoiceOrderDetailItemsWithQuatityGroupByForFactory
    {
        public int IndicoOrderID { get; set; }
        public int IndicoOrderDetailID { get; set; }
        public string OrderType { get; set; }
        public string VisualLayout { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Distributor { get; set; }
        public string Client { get; set; }
        public int ShipmentDeatil { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<decimal> FactoryPrice { get; set; }
        public string PurchaseOrder { get; set; }
        public string Fabric { get; set; }
        public string Gender { get; set; }
        public string AgeGroup { get; set; }
        public string SleeveShape { get; set; }
        public string SleeveLength { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> JKFOBCostSheetPrice { get; set; }
        public string Notes { get; set; }
    }
}
