//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetShipmentKeysView
    {
        public int ID { get; set; }
        public string ShipTo { get; set; }
        public int Shipment { get; set; }
        public System.DateTime ETD { get; set; }
        public string Port { get; set; }
        public string ShipmentMode { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
    }
}
