//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetWeeklyAddressDetailsByDistributorForIndiman
    {
        public int ID { get; set; }
        public int IndicoOrderDetailID { get; set; }
        public string Distributor { get; set; }
        public string Client { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> Qty { get; set; }
        public string GenderAgeGroup { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> IndimanPrice { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PurchaseOrder { get; set; }
        public string Fabric { get; set; }
        public string Pattern { get; set; }
        public string VisualLayout { get; set; }
        public string ItemName { get; set; }
        public string Notes { get; set; }
        public string SizeQuantities { get; set; }
        public string PatternNo { get; set; }
        public string NickName { get; set; }
        public string FabricName { get; set; }
    }
}
