//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetWeeklyAddressDetailsByHSCode
    {
        public int ID { get; set; }
        public string HSCode { get; set; }
        public string Material { get; set; }
        public string ItemName { get; set; }
        public string Gender { get; set; }
        public string ItemSubGroup { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
