//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsFromIndico
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public Nullable<System.DateTime> OrderShipmentDate { get; set; }
        public Nullable<System.DateTime> OrderDetailShipmentDate { get; set; }
        public string OrderType { get; set; }
        public string Distributor { get; set; }
        public string Client { get; set; }
        public string PurchaseOrder { get; set; }
        public string NamePrefix { get; set; }
        public string Pattern { get; set; }
        public string Fabric { get; set; }
        public string Material { get; set; }
        public string Gender { get; set; }
        public string AgeGroup { get; set; }
        public string SleeveShape { get; set; }
        public string SleeveLength { get; set; }
        public string ItemSubGroup { get; set; }
        public string SizeName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string Status { get; set; }
        public Nullable<int> PrintedCount { get; set; }
        public string PatternImagePath { get; set; }
        public string VLImagePath { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public string Notes { get; set; }
        public string PatternInvoiceNotes { get; set; }
        public string ProductNotes { get; set; }
        public Nullable<decimal> JKFOBCostSheetPrice { get; set; }
        public Nullable<decimal> IndimanCIFCostSheetPrice { get; set; }
        public string HSCode { get; set; }
        public string ItemName { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<int> DistributorClientAddressID { get; set; }
        public string DistributorClientAddressName { get; set; }
        public string DestinationPort { get; set; }
        public string ShipmentMode { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<System.DateTime> WeekEndDate { get; set; }
        public string JobName { get; set; }
    }
}
