//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.ShipmentDetails = new HashSet<ShipmentDetail>();
        }
    
        public int ID { get; set; }
        public int WeekNo { get; set; }
        public System.DateTime WeekendDate { get; set; }
        public Nullable<int> IndicoWeeklyProductionCapacityID { get; set; }
    
        public virtual ICollection<ShipmentDetail> ShipmentDetails { get; set; }
    }
}
