//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDetail
    {
        public ShipmentDetail()
        {
            this.OrderDeatilItems = new HashSet<OrderDeatilItem>();
            this.ShipmentDetailCartons = new HashSet<ShipmentDetailCarton>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int ID { get; set; }
        public int Shipment { get; set; }
        public int IndicoDistributorClientAddress { get; set; }
        public string ShipTo { get; set; }
        public string Port { get; set; }
        public string ShipmentMode { get; set; }
        public string PriceTerm { get; set; }
        public System.DateTime ETD { get; set; }
        public int Qty { get; set; }
        public int QuantityFilled { get; set; }
        public int QuantityYetToBeFilled { get; set; }
        public string InvoiceNo { get; set; }
    
        public virtual ICollection<OrderDeatilItem> OrderDeatilItems { get; set; }
        public virtual Shipment Shipment1 { get; set; }
        public virtual ICollection<ShipmentDetailCarton> ShipmentDetailCartons { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
