//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicoPacking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDetailCarton
    {
        public ShipmentDetailCarton()
        {
            this.OrderDeatilItems = new HashSet<OrderDeatilItem>();
        }
    
        public int ID { get; set; }
        public int ShipmentDetail { get; set; }
        public int Carton { get; set; }
        public int Number { get; set; }
    
        public virtual Carton Carton1 { get; set; }
        public virtual ICollection<OrderDeatilItem> OrderDeatilItems { get; set; }
        public virtual ShipmentDetail ShipmentDetail1 { get; set; }
    }
}
